x=("apple","ornage","grape","watermelon")
print(x)
print(type(x))
print(len(x))
y=("deepak",)
print(type(y))
print(x[2])
print(x[1:4])
print(x[2:])
print(x[:3])
print(x[-3:-1])
print(x[-2:])
print("ornage" in x)
print("grape" not in x)
for i in x:
    print(i)
a=list(x)
print(a)
a[1]="banana"
a.append("mango")
print(a)
a.remove("apple")
print(a)
x=tuple(a)
print(x)
print(x+y)
print(y*2)
print(y.count("deepak"))
